[package]
name = "compiler"
version = "0.1.0"
edition = "2021"
publish = false
description = "Jack compiler"

[dependencies]
tree-sitter = "0.20.3"
tree-sitter-jack = "0.1.1"
vm-translator = { path = "../vm-translator" }
